// Copyright (c) JakeSays
// SPDX-License-Identifier: MIT

using System.Text;

namespace DpdTableGenerator;

/// <summary>
/// Emits the declet tables as byte spans. A <c>ReadOnlySpan&lt;byte&gt;</c> over a
/// collection expression of constants is laid down in the assembly's data section, so the
/// tables cost nothing at startup, run no class constructor, and are never copied.
/// </summary>
public class DpdTableWriter
{
    /// <summary>Digits carried by one declet, and so bytes per entry in the first table.</summary>
    private const int DigitsPerDeclet = 3;

    /// <summary>A declet is ten bits, so an entry in the second table is two bytes.</summary>
    private const int BytesPerDeclet = 2;

    private const int BytesPerLine = 24;

    public void Write(string path)
    {
        var text = new StringBuilder();

        text.AppendLine("// <auto-generated/>");
        text.AppendLine("// Copyright (c) JakeSays");
        text.AppendLine("// SPDX-License-Identifier: MIT");
        text.AppendLine();
        text.AppendLine("// Generated by dpd-tables from the bit rules in DecletRules.cs.");
        text.AppendLine("// Do not edit: change the rules and regenerate.");
        text.AppendLine();
        text.AppendLine("namespace Decimals;");
        text.AppendLine();
        text.AppendLine("/// <summary>");
        text.AppendLine("/// The densely-packed-decimal declet tables, laid out for the representation");
        text.AppendLine("/// arithmetic works on: three digits per declet, one digit per byte.");
        text.AppendLine("/// </summary>");
        text.AppendLine("/// <remarks>");
        text.AppendLine("/// Each of these is a span over the assembly's data section rather than an array,");
        text.AppendLine("/// so nothing is allocated, no class constructor runs before a lookup, and the");
        text.AppendLine("/// bytes are read in place.");
        text.AppendLine("/// </remarks>");
        text.AppendLine("internal static class DpdTables");
        text.AppendLine("{");

        WriteDecletToBcd(text);
        text.AppendLine();
        WriteBcdToDeclet(text);
        text.AppendLine();
        WriteBinaryToBcd(text);

        text.AppendLine("}");

        File.WriteAllText(path, text.ToString());
    }

    /// <summary>
    /// Declet to its three digits, one per byte and most significant first, indexed by
    /// <c>declet * 3</c>. The three bytes read out are what a coefficient buffer wants
    /// written into it, so unpacking copies them and does no arithmetic.
    /// </summary>
    private void WriteDecletToBcd(StringBuilder text)
    {
        var table = new byte[DecletRules.DecletCount * DigitsPerDeclet];
        for (var declet = 0u; declet < DecletRules.DecletCount; declet++)
        {
            var value = DecletRules.Decode(declet);
            var position = (int)declet * DigitsPerDeclet;
            table[position] = (byte)(value / 100);
            table[position + 1] = (byte)((value / 10) % 10);
            table[position + 2] = (byte)(value % 10);
        }

        text.AppendLine("    /// <summary>");
        text.AppendLine("    /// A declet's three digits, most significant first, at <c>declet * 3</c>.");
        text.AppendLine("    /// </summary>");
        text.AppendLine("    public static ReadOnlySpan<byte> DecletToBcd =>");
        WriteBytes(text, table);
    }

    /// <summary>
    /// Three digits to the canonical declet carrying them, indexed by the digits held one
    /// per nibble and most significant first, two bytes per entry least significant first.
    /// Nibble combinations holding a digit above nine cannot occur in a coefficient and
    /// stay zero.
    /// </summary>
    private void WriteBcdToDeclet(StringBuilder text)
    {
        var table = new byte[DecletRules.BcdIndexCount * BytesPerDeclet];
        for (var high = 0u; high < 10; high++)
        {
            for (var middle = 0u; middle < 10; middle++)
            {
                for (var low = 0u; low < 10; low++)
                {
                    var declet = DecletRules.Encode((high * 100) + (middle * 10) + low);
                    var index = (high << 8) | (middle << 4) | low;
                    var position = (int)index * BytesPerDeclet;
                    table[position] = (byte)declet;
                    table[position + 1] = (byte)(declet >> 8);
                }
            }
        }

        text.AppendLine("    /// <summary>");
        text.AppendLine("    /// The canonical declet for three digits held one per nibble, two bytes per");
        text.AppendLine("    /// entry and least significant first, at <c>nibbles * 2</c>.");
        text.AppendLine("    /// </summary>");
        text.AppendLine("    public static ReadOnlySpan<byte> BcdToDeclet =>");
        WriteBytes(text, table);
    }

    /// <summary>
    /// A value 0 through 999 as three digits, one per byte and most significant first.
    /// Multiplication works in base-billion limbs and has to lay each one back out as nine
    /// digits; this turns that into two divisions and three table reads rather than nine
    /// divisions. It is decNumber's <c>BIN2BCD8</c>.
    /// </summary>
    private void WriteBinaryToBcd(StringBuilder text)
    {
        var table = new byte[DecletRules.ValueCount * DigitsPerDeclet];
        for (var value = 0u; value < DecletRules.ValueCount; value++)
        {
            var position = (int)value * DigitsPerDeclet;
            table[position] = (byte)(value / 100);
            table[position + 1] = (byte)((value / 10) % 10);
            table[position + 2] = (byte)(value % 10);
        }

        text.AppendLine("    /// <summary>");
        text.AppendLine("    /// A value 0 through 999 as three digits, most significant first, at");
        text.AppendLine("    /// <c>value * 3</c>.");
        text.AppendLine("    /// </summary>");
        text.AppendLine("    public static ReadOnlySpan<byte> BinaryToBcd =>");
        WriteBytes(text, table);
    }

    private void WriteBytes(StringBuilder text, byte[] table)
    {
        text.AppendLine("    [");

        for (var position = 0; position < table.Length; position += BytesPerLine)
        {
            var remaining = Math.Min(BytesPerLine, table.Length - position);
            text.Append("        ");
            for (var offset = 0; offset < remaining; offset++)
            {
                text.Append("0x");
                text.Append(table[position + offset].ToString("X2"));
                if (position + offset < table.Length - 1)
                {
                    text.Append(',');
                }

                if (offset < remaining - 1)
                {
                    text.Append(' ');
                }
            }

            text.AppendLine();
        }

        text.AppendLine("    ];");
    }
}
