<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Decimals.DecTest</RootNamespace>
    <AssemblyName>dectest-cs</AssemblyName>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Decimals.Conformance\Decimals.Conformance.csproj" />
  </ItemGroup>

</Project>
