<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Decimals.Conformance</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Decimal32\Decimal32.csproj" />
    <ProjectReference Include="..\Decimal64\Decimal64.csproj" />
    <ProjectReference Include="..\Decimal128\Decimal128.csproj" />
  </ItemGroup>

</Project>
